// Script to generate comprehensive One Piece TCG dataset for Grand Line Vault
const fs = require('fs');
const path = require('path');

const SETS = [
  { id: 'ALL', name: 'Todas las Expansiones', code: 'ALL' },
  { id: 'OP-01', name: 'OP-01: Romance Dawn', code: 'OP01', totalCards: 121, releaseYear: 2022 },
  { id: 'OP-02', name: 'OP-02: Paramount War', code: 'OP02', totalCards: 121, releaseYear: 2022 },
  { id: 'OP-03', name: 'OP-03: Pillars of Strength', code: 'OP03', totalCards: 127, releaseYear: 2023 },
  { id: 'OP-04', name: 'OP-04: Kingdoms of Intrigue', code: 'OP04', totalCards: 124, releaseYear: 2023 },
  { id: 'OP-05', name: 'OP-05: Awakening of the New Era', code: 'OP05', totalCards: 126, releaseYear: 2023 },
  { id: 'OP-06', name: 'OP-06: Wings of the Captain', code: 'OP06', totalCards: 126, releaseYear: 2024 },
  { id: 'OP-07', name: 'OP-07: 500 Years in the Future', code: 'OP07', totalCards: 126, releaseYear: 2024 },
  { id: 'OP-08', name: 'OP-08: Two Legends', code: 'OP08', totalCards: 126, releaseYear: 2024 },
  { id: 'OP-09', name: 'OP-09: The Four Emperors', code: 'OP09', totalCards: 126, releaseYear: 2024 },
  { id: 'ST-01', name: 'ST-01: Straw Hat Crew', code: 'ST01', totalCards: 17, releaseYear: 2022 },
  { id: 'ST-02', name: 'ST-02: Worst Generation', code: 'ST02', totalCards: 17, releaseYear: 2022 },
  { id: 'ST-10', name: 'ST-10: The Three Captains', code: 'ST10', totalCards: 17, releaseYear: 2023 },
];

const COLORS = [
  { id: 'Red', name: 'Rojo', hex: '#ef4444', border: 'border-red-500', bg: 'bg-red-500/20', text: 'text-red-400' },
  { id: 'Green', name: 'Verde', hex: '#22c55e', border: 'border-green-500', bg: 'bg-green-500/20', text: 'text-green-400' },
  { id: 'Blue', name: 'Azul', hex: '#3b82f6', border: 'border-blue-500', bg: 'bg-blue-500/20', text: 'text-blue-400' },
  { id: 'Purple', name: 'Púrpura', hex: '#a855f7', border: 'border-purple-500', bg: 'bg-purple-500/20', text: 'text-purple-400' },
  { id: 'Black', name: 'Negro', hex: '#71717a', border: 'border-neutral-500', bg: 'bg-neutral-500/20', text: 'text-neutral-300' },
  { id: 'Yellow', name: 'Amarillo', hex: '#eab308', border: 'border-yellow-500', bg: 'bg-yellow-500/20', text: 'text-yellow-400' },
];

const RARITIES = [
  { id: 'L', name: 'Leader', badgeColor: 'bg-amber-600 text-white' },
  { id: 'C', name: 'Common', badgeColor: 'bg-neutral-700 text-neutral-200' },
  { id: 'UC', name: 'Uncommon', badgeColor: 'bg-teal-700 text-white' },
  { id: 'R', name: 'Rare', badgeColor: 'bg-blue-600 text-white' },
  { id: 'SR', name: 'Super Rare', badgeColor: 'bg-purple-600 text-white' },
  { id: 'SEC', name: 'Secret Rare', badgeColor: 'bg-rose-600 text-white ring-1 ring-rose-400' },
  { id: 'SP', name: 'Special Rare / Manga', badgeColor: 'bg-gradient-to-r from-amber-400 via-rose-500 to-purple-600 text-white font-bold' },
];

const RAW_CARDS = [
  // ==========================================
  // OP-01: ROMANCE DAWN
  // ==========================================
  {
    id: 'OP01-001',
    set: 'OP-01',
    name: 'Roronoa Zoro',
    title: 'Pirate Hunter',
    category: 'Leader',
    color: 'Red',
    type: 'Supernovas / Straw Hat Crew',
    cost: null,
    life: 5,
    power: 5000,
    counter: null,
    rarity: 'L',
    effect: '[DON!! x1] [Your Turn] All of your Characters gain +1000 power.',
    attribute: 'Slash',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP01-001',
    isAltArt: false,
    cardtraderSearch: 'Roronoa Zoro OP01-001',
    marketPriceEstimated: 14.50,
  },
  {
    id: 'OP01-002',
    set: 'OP-01',
    name: 'Trafalgar Law',
    title: 'Surgeon of Death',
    category: 'Leader',
    color: 'Red / Green',
    type: 'Heart Pirates / Supernovas',
    cost: null,
    life: 4,
    power: 5000,
    counter: null,
    rarity: 'L',
    effect: '[Activate: Main] [Once Per Turn] (2): If you have 5 Characters, return 1 of your Characters to the owner\'s hand. Then, play up to 1 Character with a cost of 4 or less from your hand with a color different from the returned Character.',
    attribute: 'Slash',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP01-002',
    isAltArt: false,
    cardtraderSearch: 'Trafalgar Law OP01-002',
    marketPriceEstimated: 22.00,
  },
  {
    id: 'OP01-004',
    set: 'OP-01',
    name: 'Monkey.D.Luffy',
    title: 'Captain',
    category: 'Leader',
    color: 'Red',
    type: 'Supernovas / Straw Hat Crew',
    cost: null,
    life: 5,
    power: 5000,
    counter: null,
    rarity: 'L',
    effect: '[Activate: Main] [Once Per Turn] Give this Leader or 1 of your Characters up to 1 rested DON!! card.',
    attribute: 'Strike',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP01-004',
    isAltArt: false,
    cardtraderSearch: 'Monkey D Luffy OP01-004',
    marketPriceEstimated: 4.80,
  },
  {
    id: 'OP01-005',
    set: 'OP-01',
    name: 'Jinbe',
    title: 'Knight of the Sea',
    category: 'Character',
    color: 'Red',
    type: 'Fish-Man / Straw Hat Crew',
    cost: 4,
    life: null,
    power: 5000,
    counter: 1000,
    rarity: 'R',
    effect: '[DON!! x1] [When Attacking] Give up to 1 of your opponent\'s Characters -2000 power during this turn.',
    attribute: 'Strike',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP01-005',
    isAltArt: false,
    cardtraderSearch: 'Jinbe OP01-005',
    marketPriceEstimated: 3.50,
  },
  {
    id: 'OP01-016',
    set: 'OP-01',
    name: 'Nami',
    title: 'Cat Burglar',
    category: 'Character',
    color: 'Red',
    type: 'Straw Hat Crew',
    cost: 1,
    life: null,
    power: 2000,
    counter: 1000,
    rarity: 'R',
    effect: '[On Play] Look at 5 cards from the top of your deck; reveal up to 1 {Straw Hat Crew} type card other than [Nami] and add it to your hand. Place the rest at the bottom of your deck in any order.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP01-016',
    isAltArt: false,
    cardtraderSearch: 'Nami OP01-016',
    marketPriceEstimated: 18.00,
  },
  {
    id: 'OP01-025',
    set: 'OP-01',
    name: 'Roronoa Zoro (Rush)',
    title: 'Pirate Hunter',
    category: 'Character',
    color: 'Red',
    type: 'Supernovas / Straw Hat Crew',
    cost: 3,
    life: null,
    power: 5000,
    counter: null,
    rarity: 'SR',
    effect: '<Rush> (This card can attack on the turn in which it is played.)',
    attribute: 'Slash',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP01-025',
    isAltArt: false,
    cardtraderSearch: 'Roronoa Zoro OP01-025',
    marketPriceEstimated: 28.50,
  },
  {
    id: 'OP01-026',
    set: 'OP-01',
    name: 'Roronoa Zoro (Alt-Art Parallel)',
    title: 'Straw Hat Swordsman',
    category: 'Character',
    color: 'Red',
    type: 'Supernovas / Straw Hat Crew',
    cost: 3,
    life: null,
    power: 5000,
    counter: null,
    rarity: 'SR',
    effect: '<Rush> (This card can attack on the turn in which it is played.)',
    attribute: 'Slash',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP01-026',
    isAltArt: true,
    cardtraderSearch: 'Roronoa Zoro OP01-025 parallel',
    marketPriceEstimated: 95.00,
  },
  {
    id: 'OP01-029',
    set: 'OP-01',
    name: 'Radical Beam!!',
    title: 'Franky Special',
    category: 'Event',
    color: 'Red',
    type: 'Straw Hat Crew',
    cost: 1,
    life: null,
    power: null,
    counter: null,
    rarity: 'UC',
    effect: '[Counter] Up to 1 of your Leader or Character cards gains +2000 power during this battle. Then, if you have 2 or fewer Life cards, that card gains an additional +2000 power.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP01-029',
    isAltArt: false,
    cardtraderSearch: 'Radical Beam OP01-029',
    marketPriceEstimated: 5.20,
  },
  {
    id: 'OP01-047',
    set: 'OP-01',
    name: 'Trafalgar Law (Blocker)',
    title: 'Surgeon of Death',
    category: 'Character',
    color: 'Green',
    type: 'Heart Pirates / Supernovas',
    cost: 5,
    life: null,
    power: 6000,
    counter: 1000,
    rarity: 'SR',
    effect: '<Blocker> [On Play] Return 1 of your Characters to the owner\'s hand: Play up to 1 Character card with a cost of 3 or less from your hand.',
    attribute: 'Slash',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP01-047',
    isAltArt: false,
    cardtraderSearch: 'Trafalgar Law OP01-047',
    marketPriceEstimated: 16.00,
  },
  {
    id: 'OP01-054',
    set: 'OP-01',
    name: 'Kozuki Oden',
    title: 'Lord of Kuri',
    category: 'Leader',
    color: 'Green',
    type: 'Land of Wano / Kozuki Clan',
    cost: null,
    life: 5,
    power: 5000,
    counter: null,
    rarity: 'L',
    effect: '[Activate: Main] [Once Per Turn] Trash 1 {Land of Wano} type card from your hand: Set up to 2 of your DON!! cards as active.',
    attribute: 'Slash',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP01-054',
    isAltArt: false,
    cardtraderSearch: 'Kozuki Oden OP01-054',
    marketPriceEstimated: 6.50,
  },
  {
    id: 'OP01-060',
    set: 'OP-01',
    name: 'Donquixote Doflamingo',
    title: 'Heavenly Demon',
    category: 'Leader',
    color: 'Blue',
    type: 'The Seven Warlords of the Sea / Donquixote Pirates',
    cost: null,
    life: 5,
    power: 5000,
    counter: null,
    rarity: 'L',
    effect: '[DON!! x2] [When Attacking] (1): Look at up to 5 cards from the top of your deck and place them at the top or bottom of your deck in any order. Then, reveal the top card of your deck. If that card is a {The Seven Warlords of the Sea} type Character card with a cost of 4 or less, you may play it rested.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP01-060',
    isAltArt: false,
    cardtraderSearch: 'Donquixote Doflamingo OP01-060',
    marketPriceEstimated: 12.00,
  },
  {
    id: 'OP01-070',
    set: 'OP-01',
    name: 'Dracule Mihawk',
    title: 'Hawk Eyes',
    category: 'Character',
    color: 'Blue',
    type: 'The Seven Warlords of the Sea',
    cost: 9,
    life: null,
    power: 9000,
    counter: null,
    rarity: 'SR',
    effect: '[On Play] Place up to 1 Character with a cost of 7 or less at the bottom of the owner\'s deck.',
    attribute: 'Slash',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP01-070',
    isAltArt: false,
    cardtraderSearch: 'Dracule Mihawk OP01-070',
    marketPriceEstimated: 24.00,
  },
  {
    id: 'OP01-094',
    set: 'OP-01',
    name: 'Kaido',
    title: 'King of the Beasts',
    category: 'Character',
    color: 'Purple',
    type: 'The Four Emperors / Animal Kingdom Pirates',
    cost: 10,
    life: null,
    power: 12000,
    counter: null,
    rarity: 'SR',
    effect: '[On Play] DON!! -6: K.O. all Characters other than this card.',
    attribute: 'Strike',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP01-094',
    isAltArt: false,
    cardtraderSearch: 'Kaido OP01-094',
    marketPriceEstimated: 19.50,
  },
  {
    id: 'OP01-120',
    set: 'OP-01',
    name: 'Shanks (Secret)',
    title: 'Red Hair',
    category: 'Character',
    color: 'Red',
    type: 'The Four Emperors / Red Hair Pirates',
    cost: 9,
    life: null,
    power: 10000,
    counter: null,
    rarity: 'SEC',
    effect: '<Rush> [When Attacking] This Character cannot be blocked by Characters with 2000 or less power.',
    attribute: 'Slash',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP01-120',
    isAltArt: false,
    cardtraderSearch: 'Shanks OP01-120',
    marketPriceEstimated: 42.00,
  },
  {
    id: 'OP01-121',
    set: 'OP-01',
    name: 'Yamato (Secret)',
    title: 'Daughter of Kaido',
    category: 'Character',
    color: 'Green',
    type: 'Land of Wano',
    cost: 5,
    life: null,
    power: 5000,
    counter: 1000,
    rarity: 'SEC',
    effect: '<Double Attack> <Banish> (When this card deals damage, the target card is trashed without activating its trigger.)',
    attribute: 'Strike',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP01-121',
    isAltArt: false,
    cardtraderSearch: 'Yamato OP01-121',
    marketPriceEstimated: 35.00,
  },

  // ==========================================
  // OP-02: PARAMOUNT WAR
  // ==========================================
  {
    id: 'OP02-001',
    set: 'OP-02',
    name: 'Edward.Newgate',
    title: 'Whitebeard',
    category: 'Leader',
    color: 'Red',
    type: 'The Four Emperors / Whitebeard Pirates',
    cost: null,
    life: 6,
    power: 6000,
    counter: null,
    rarity: 'L',
    effect: '[End of Your Turn] Add 1 card from the top of your Life cards to your hand.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP02-001',
    isAltArt: false,
    cardtraderSearch: 'Edward Newgate OP02-001',
    marketPriceEstimated: 15.00,
  },
  {
    id: 'OP02-004',
    set: 'OP-02',
    name: 'Edward.Newgate (9-Cost)',
    title: 'Strongest Man in the World',
    category: 'Character',
    color: 'Red',
    type: 'The Four Emperors / Whitebeard Pirates',
    cost: 9,
    life: null,
    power: 10000,
    counter: null,
    rarity: 'SR',
    effect: '[On Play] During this turn, your Leader cannot lose Life from your opponent\'s effects or attacks, and your Leader gains +2000 power until the start of your next turn.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP02-004',
    isAltArt: false,
    cardtraderSearch: 'Edward Newgate OP02-004',
    marketPriceEstimated: 32.00,
  },
  {
    id: 'OP02-013',
    set: 'OP-02',
    name: 'Portgas.D.Ace',
    title: 'Fire Fist',
    category: 'Character',
    color: 'Red',
    type: 'Whitebeard Pirates',
    cost: 7,
    life: null,
    power: 7000,
    counter: null,
    rarity: 'SR',
    effect: '<Rush> [On Play] Give up to 2 of your opponent\'s Characters -3000 power during this turn.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP02-013',
    isAltArt: false,
    cardtraderSearch: 'Portgas D Ace OP02-013',
    marketPriceEstimated: 26.00,
  },
  {
    id: 'OP02-013-MANGA',
    set: 'OP-02',
    name: 'Portgas.D.Ace (Manga Rare)',
    title: 'Manga Parallel Art',
    category: 'Character',
    color: 'Red',
    type: 'Whitebeard Pirates',
    cost: 7,
    life: null,
    power: 7000,
    counter: null,
    rarity: 'SP',
    effect: '<Rush> [On Play] Give up to 2 of your opponent\'s Characters -3000 power during this turn.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP02-013_p2',
    isAltArt: true,
    cardtraderSearch: 'Portgas D Ace manga OP02-013',
    marketPriceEstimated: 850.00,
  },
  {
    id: 'OP02-071',
    set: 'OP-02',
    name: 'Smoker',
    title: 'White Hunter',
    category: 'Leader',
    color: 'Black',
    type: 'Navy',
    cost: null,
    life: 5,
    power: 5000,
    counter: null,
    rarity: 'L',
    effect: '[DON!! x1] [Activate: Main] [Once Per Turn] Give up to 1 of your opponent\'s Characters -1 cost during this turn. Then, if there is a Character with a cost of 0, this Leader gains +1000 power during this turn.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP02-071',
    isAltArt: false,
    cardtraderSearch: 'Smoker OP02-071',
    marketPriceEstimated: 8.50,
  },
  {
    id: 'OP02-096',
    set: 'OP-02',
    name: 'Borsalino (Blocker)',
    title: 'Kizaru',
    category: 'Character',
    color: 'Black',
    type: 'Navy',
    cost: 4,
    life: null,
    power: 5000,
    counter: 1000,
    rarity: 'SR',
    effect: '<Blocker> [Opponent\'s Turn] This Character gains +1000 power and cannot be K.O.\'d by effects.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP02-096',
    isAltArt: false,
    cardtraderSearch: 'Borsalino OP02-096',
    marketPriceEstimated: 29.00,
  },
  {
    id: 'OP02-099',
    set: 'OP-02',
    name: 'Sakazuki',
    title: 'Akainu',
    category: 'Character',
    color: 'Black',
    type: 'Navy',
    cost: 6,
    life: null,
    power: 7000,
    counter: null,
    rarity: 'SR',
    effect: '[On Play] K.O. up to 1 of your opponent\'s Characters with a cost of 5 or less.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP02-099',
    isAltArt: false,
    cardtraderSearch: 'Sakazuki OP02-099',
    marketPriceEstimated: 12.00,
  },
  {
    id: 'OP02-114',
    set: 'OP-02',
    name: 'Borsalino',
    title: 'Navy Admiral',
    category: 'Character',
    color: 'Black',
    type: 'Navy',
    cost: 7,
    life: null,
    power: 8000,
    counter: null,
    rarity: 'R',
    effect: '[On Play] K.O. up to 1 of your opponent\'s Characters with a cost of 4 or less.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP02-114',
    isAltArt: false,
    cardtraderSearch: 'Borsalino OP02-114',
    marketPriceEstimated: 6.50,
  },
  {
    id: 'OP02-120',
    set: 'OP-02',
    name: 'Uta (Secret)',
    title: 'World Diva',
    category: 'Character',
    color: 'Purple',
    type: 'Film',
    cost: 8,
    life: null,
    power: 8000,
    counter: null,
    rarity: 'SEC',
    effect: '<Blocker> [On Play] DON!! -2: Rest up to 2 of your opponent\'s Characters with a cost of 5 or less.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP02-120',
    isAltArt: false,
    cardtraderSearch: 'Uta OP02-120',
    marketPriceEstimated: 38.00,
  },
  {
    id: 'OP02-121',
    set: 'OP-02',
    name: 'Kuzan (10-Cost Secret)',
    title: 'Aokiji',
    category: 'Character',
    color: 'Black',
    type: 'Navy',
    cost: 10,
    life: null,
    power: 10000,
    counter: null,
    rarity: 'SEC',
    effect: '[Your Turn] All of your opponent\'s Characters get -5 cost. [Activate: Main] [Once Per Turn] K.O. up to 1 of your opponent\'s Characters with a cost of 0.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP02-121',
    isAltArt: false,
    cardtraderSearch: 'Kuzan OP02-121',
    marketPriceEstimated: 55.00,
  },

  // ==========================================
  // OP-03: PILLARS OF STRENGTH
  // ==========================================
  {
    id: 'OP03-001',
    set: 'OP-03',
    name: 'Portgas.D.Ace',
    title: 'Commander',
    category: 'Leader',
    color: 'Red',
    type: 'Whitebeard Pirates',
    cost: null,
    life: 5,
    power: 5000,
    counter: null,
    rarity: 'L',
    effect: '[When Attacking] Reveal 1 card from the top of your deck. If that card is an Event or Stage card, you may add it to your hand.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP03-001',
    isAltArt: false,
    cardtraderSearch: 'Portgas D Ace OP03-001',
    marketPriceEstimated: 9.00,
  },
  {
    id: 'OP03-040',
    set: 'OP-03',
    name: 'Nami (Alt Win Leader)',
    title: 'Cat Burglar',
    category: 'Leader',
    color: 'Blue',
    type: 'East Blue / Straw Hat Crew',
    cost: null,
    life: 5,
    power: 5000,
    counter: null,
    rarity: 'L',
    effect: '[Game Win Condition] When your deck has 0 cards, you win the match instead of losing. [When Attacking] Trash 1 card from the top of your deck.',
    attribute: 'Wisdom',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP03-040',
    isAltArt: false,
    cardtraderSearch: 'Nami OP03-040',
    marketPriceEstimated: 35.00,
  },
  {
    id: 'OP03-076',
    set: 'OP-03',
    name: 'Rob Lucci',
    title: 'CP9 Agent',
    category: 'Character',
    color: 'Black',
    type: 'CP9',
    cost: 6,
    life: null,
    power: 7000,
    counter: 1000,
    rarity: 'SR',
    effect: '[On Play] Trash 2 cards with the {CP} type from your hand or trash: K.O. up to 1 of your opponent\'s Characters with a cost of 5 or less and up to 1 with a cost of 3 or less.',
    attribute: 'Slash',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP03-076',
    isAltArt: false,
    cardtraderSearch: 'Rob Lucci OP03-076',
    marketPriceEstimated: 18.00,
  },
  {
    id: 'OP03-077',
    set: 'OP-03',
    name: 'Charlotte Linlin',
    title: 'Big Mom',
    category: 'Leader',
    color: 'Yellow',
    type: 'The Four Emperors / Big Mom Pirates',
    cost: null,
    life: 4,
    power: 5000,
    counter: null,
    rarity: 'L',
    effect: '[DON!! x2] [When Attacking] (1): If you have 2 or fewer Life cards, add 1 card from the top of your deck to the top of your Life cards.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP03-077',
    isAltArt: false,
    cardtraderSearch: 'Charlotte Linlin OP03-077',
    marketPriceEstimated: 8.00,
  },
  {
    id: 'OP03-099',
    set: 'OP-03',
    name: 'Charlotte Katakuri',
    title: 'Sweet Commander',
    category: 'Leader',
    color: 'Yellow',
    type: 'Big Mom Pirates',
    cost: null,
    life: 5,
    power: 5000,
    counter: null,
    rarity: 'L',
    effect: '[DON!! x1] [When Attacking] Look at up to 1 Life card from the top of your or your opponent\'s Life cards, and place it at the top or bottom of the Life cards. Then, this Leader gains +1000 power during this turn.',
    attribute: 'Strike',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP03-099',
    isAltArt: false,
    cardtraderSearch: 'Charlotte Katakuri OP03-099',
    marketPriceEstimated: 32.00,
  },
  {
    id: 'OP03-112',
    set: 'OP-03',
    name: 'Charlotte Pudding',
    title: 'Chocolatier',
    category: 'Character',
    color: 'Yellow',
    type: 'Big Mom Pirates',
    cost: 1,
    life: null,
    power: 2000,
    counter: 1000,
    rarity: 'R',
    effect: '[On Play] Look at 4 cards from the top of your deck; reveal up to 1 {Big Mom Pirates} type card and add it to your hand.',
    attribute: 'Wisdom',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP03-112',
    isAltArt: false,
    cardtraderSearch: 'Charlotte Pudding OP03-112',
    marketPriceEstimated: 12.00,
  },
  {
    id: 'OP03-114',
    set: 'OP-03',
    name: 'Charlotte Linlin (10-Cost)',
    title: 'Soul Pocus',
    category: 'Character',
    color: 'Yellow',
    type: 'The Four Emperors / Big Mom Pirates',
    cost: 10,
    life: null,
    power: 12000,
    counter: null,
    rarity: 'SR',
    effect: '[On Play] Put 1 card from the top of your opponent\'s Life cards into their trash, and add 1 card from the top of your deck to the top of your Life cards.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP03-114',
    isAltArt: false,
    cardtraderSearch: 'Charlotte Linlin OP03-114',
    marketPriceEstimated: 34.00,
  },
  {
    id: 'OP03-122',
    set: 'OP-03',
    name: 'Sogeking',
    title: 'King of Snipers',
    category: 'Character',
    color: 'Blue',
    type: 'Sniper Island',
    cost: 7,
    life: null,
    power: 7000,
    counter: null,
    rarity: 'SEC',
    effect: '[On Play] Return up to 1 Character with a cost of 6 or less to the owner\'s hand. Then, draw 2 cards and trash 2 cards from your hand.',
    attribute: 'Ranged',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP03-122',
    isAltArt: false,
    cardtraderSearch: 'Sogeking OP03-122',
    marketPriceEstimated: 25.00,
  },
  {
    id: 'OP03-122-MANGA',
    set: 'OP-03',
    name: 'Sogeking (Manga Rare)',
    title: 'Manga Parallel Art',
    category: 'Character',
    color: 'Blue',
    type: 'Sniper Island',
    cost: 7,
    life: null,
    power: 7000,
    counter: null,
    rarity: 'SP',
    effect: '[On Play] Return up to 1 Character with a cost of 6 or less to the owner\'s hand. Then, draw 2 cards and trash 2 cards from your hand.',
    attribute: 'Ranged',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP03-122_p2',
    isAltArt: true,
    cardtraderSearch: 'Sogeking manga OP03-122',
    marketPriceEstimated: 750.00,
  },

  // ==========================================
  // OP-04: KINGDOMS OF INTRIGUE
  // ==========================================
  {
    id: 'OP04-001',
    set: 'OP-04',
    name: 'Nefertari Vivi',
    title: 'Princess of Alabasta',
    category: 'Leader',
    color: 'Red / Blue',
    type: 'Alabasta',
    cost: null,
    life: 5,
    power: 5000,
    counter: null,
    rarity: 'L',
    effect: '[This Leader cannot attack.] [Activate: Main] [Once Per Turn] (2): Draw 1 card and give up to 1 of your Characters <Rush> during this turn.',
    attribute: 'Slash',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP04-001',
    isAltArt: false,
    cardtraderSearch: 'Nefertari Vivi OP04-001',
    marketPriceEstimated: 7.50,
  },
  {
    id: 'OP04-039',
    set: 'OP-04',
    name: 'Rebecca',
    title: 'Undefeated Woman',
    category: 'Leader',
    color: 'Blue / Black',
    type: 'Dressrosa',
    cost: null,
    life: 4,
    power: 5000,
    counter: null,
    rarity: 'L',
    effect: '[This Leader cannot attack.] [Activate: Main] [Once Per Turn] (1): If you have 6 or fewer cards in hand, look at 2 cards from the top of your deck; reveal up to 1 {Dressrosa} type card and add it to your hand.',
    attribute: 'Slash',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP04-039',
    isAltArt: false,
    cardtraderSearch: 'Rebecca OP04-039',
    marketPriceEstimated: 14.00,
  },
  {
    id: 'OP04-083',
    set: 'OP-04',
    name: 'Sabo (Blocker)',
    title: 'Chief of Staff',
    category: 'Character',
    color: 'Black',
    type: 'Revolutionary Army',
    cost: 5,
    life: null,
    power: 6000,
    counter: 1000,
    rarity: 'SR',
    effect: '<Blocker> [On Play] Draw 2 cards and trash 2 cards from your hand. Then, none of your Characters can be K.O.\'d by effects until the start of your next turn.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP04-083',
    isAltArt: false,
    cardtraderSearch: 'Sabo OP04-083',
    marketPriceEstimated: 26.00,
  },
  {
    id: 'OP04-083-MANGA',
    set: 'OP-04',
    name: 'Sabo (Manga Rare)',
    title: 'Manga Parallel Art',
    category: 'Character',
    color: 'Black',
    type: 'Revolutionary Army',
    cost: 5,
    life: null,
    power: 6000,
    counter: 1000,
    rarity: 'SP',
    effect: '<Blocker> [On Play] Draw 2 cards and trash 2 cards from your hand. Then, none of your Characters can be K.O.\'d by effects until the start of your next turn.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP04-083_p2',
    isAltArt: true,
    cardtraderSearch: 'Sabo manga OP04-083',
    marketPriceEstimated: 650.00,
  },
  {
    id: 'OP04-119',
    set: 'OP-04',
    name: 'Donquixote Rosinante (Corazon)',
    title: 'Silent Guardian',
    category: 'Character',
    color: 'Green',
    type: 'Navy / Donquixote Pirates',
    cost: 8,
    life: null,
    power: 8000,
    counter: null,
    rarity: 'SEC',
    effect: '<Blocker> [End of Your Turn] Set this Character as active.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP04-119',
    isAltArt: false,
    cardtraderSearch: 'Donquixote Rosinante OP04-119',
    marketPriceEstimated: 22.00,
  },

  // ==========================================
  // OP-05: AWAKENING OF THE NEW ERA
  // ==========================================
  {
    id: 'OP05-001',
    set: 'OP-05',
    name: 'Sabo (Leader)',
    title: 'Flame Emperor',
    category: 'Leader',
    color: 'Red / Black',
    type: 'Revolutionary Army',
    cost: null,
    life: 4,
    power: 5000,
    counter: null,
    rarity: 'L',
    effect: '[DON!! x1] [Activate: Main] [Once Per Turn] Give up to 1 of your Characters with 5000 or more power +1000 power during this turn.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP05-001',
    isAltArt: false,
    cardtraderSearch: 'Sabo OP05-001',
    marketPriceEstimated: 12.00,
  },
  {
    id: 'OP05-041',
    set: 'OP-05',
    name: 'Sakazuki (Navy Leader)',
    title: 'Fleet Admiral',
    category: 'Leader',
    color: 'Blue / Black',
    type: 'Navy',
    cost: null,
    life: 4,
    power: 5000,
    counter: null,
    rarity: 'L',
    effect: '[Activate: Main] [Once Per Turn] Trash 1 card from your hand: Draw 1 card. [When Attacking] Give up to 1 of your opponent\'s Characters -1 cost during this turn.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP05-041',
    isAltArt: false,
    cardtraderSearch: 'Sakazuki OP05-041',
    marketPriceEstimated: 28.00,
  },
  {
    id: 'OP05-060',
    set: 'OP-05',
    name: 'Monkey.D.Luffy (Gear 5)',
    title: 'Sun God Nika',
    category: 'Character',
    color: 'Purple',
    type: 'Straw Hat Crew',
    cost: 10,
    life: null,
    power: 12000,
    counter: null,
    rarity: 'SEC',
    effect: '[On Play] Return all DON!! cards from your field to your DON!! deck: Take an extra turn after this one! This Character cannot attack during the extra turn.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP05-060',
    isAltArt: false,
    cardtraderSearch: 'Monkey D Luffy Gear 5 OP05-060',
    marketPriceEstimated: 65.00,
  },
  {
    id: 'OP05-060-MANGA',
    set: 'OP-05',
    name: 'Monkey.D.Luffy (Gear 5 Manga Rare)',
    title: 'Awakening of the New Era',
    category: 'Character',
    color: 'Purple',
    type: 'Straw Hat Crew',
    cost: 10,
    life: null,
    power: 12000,
    counter: null,
    rarity: 'SP',
    effect: '[On Play] Return all DON!! cards from your field to your DON!! deck: Take an extra turn after this one!',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP05-060_p2',
    isAltArt: true,
    cardtraderSearch: 'Monkey D Luffy Gear 5 Manga OP05-060',
    marketPriceEstimated: 2800.00,
  },
  {
    id: 'OP05-069',
    set: 'OP-05',
    name: 'Trafalgar Law',
    title: 'Surgeon of Death',
    category: 'Character',
    color: 'Purple',
    type: 'Heart Pirates / Supernovas',
    cost: 4,
    life: null,
    power: 5000,
    counter: 1000,
    rarity: 'SR',
    effect: '[On Play] DON!! -1: Your opponent puts 2 cards from their hand at the bottom of their deck in any order.',
    attribute: 'Slash',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP05-069',
    isAltArt: false,
    cardtraderSearch: 'Trafalgar Law OP05-069',
    marketPriceEstimated: 21.00,
  },
  {
    id: 'OP05-074',
    set: 'OP-05',
    name: 'Eustass"Captain"Kid',
    title: 'Punk Rotten',
    category: 'Character',
    color: 'Purple',
    type: 'Kid Pirates / Supernovas',
    cost: 8,
    life: null,
    power: 8000,
    counter: 1000,
    rarity: 'SR',
    effect: '<Blocker> [Your Turn] When you take a DON!! card from your field, add 1 active DON!! card from your DON!! deck.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP05-074',
    isAltArt: false,
    cardtraderSearch: 'Eustass Captain Kid OP05-074',
    marketPriceEstimated: 24.50,
  },
  {
    id: 'OP05-098',
    set: 'OP-05',
    name: 'Enel',
    title: 'God of Skypiea',
    category: 'Leader',
    color: 'Yellow',
    type: 'Sky Island',
    cost: null,
    life: 4,
    power: 5000,
    counter: null,
    rarity: 'L',
    effect: '[Opponent\'s Turn] [Once Per Turn] When your Life drops to 0, trash 1 card from your hand: Add 1 card from the top of your deck to the top of your Life cards.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP05-098',
    isAltArt: false,
    cardtraderSearch: 'Enel OP05-098',
    marketPriceEstimated: 35.00,
  },
  {
    id: 'OP05-115',
    set: 'OP-05',
    name: 'Two-Sword Style Draw Slash',
    title: 'Tower Climb',
    category: 'Event',
    color: 'Green',
    type: 'Straw Hat Crew',
    cost: 2,
    life: null,
    power: null,
    counter: null,
    rarity: 'R',
    effect: '[Main] Rest up to 1 of your opponent\'s Characters with a cost of 4 or less. Then, K.O. up to 1 of your opponent\'s rested Characters with a cost of 2 or less.',
    attribute: 'Slash',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP05-115',
    isAltArt: false,
    cardtraderSearch: 'Two-Sword Style Draw Slash OP05-115',
    marketPriceEstimated: 2.50,
  },
  {
    id: 'OP05-118',
    set: 'OP-05',
    name: 'Kaido (Dragon Form)',
    title: 'Supreme Beast',
    category: 'Character',
    color: 'Blue',
    type: 'The Four Emperors / Animal Kingdom Pirates',
    cost: 10,
    life: null,
    power: 12000,
    counter: null,
    rarity: 'SEC',
    effect: '[On Play] Return up to 1 Character with a cost of 8 or less to the bottom of the owner\'s deck. Then, draw 1 card.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP05-118',
    isAltArt: false,
    cardtraderSearch: 'Kaido OP05-118',
    marketPriceEstimated: 44.00,
  },

  // ==========================================
  // OP-06: WINGS OF THE CAPTAIN
  // ==========================================
  {
    id: 'OP06-001',
    set: 'OP-06',
    name: 'Uta',
    title: 'World Diva',
    category: 'Leader',
    color: 'Red / Purple',
    type: 'FILM',
    cost: null,
    life: 4,
    power: 5000,
    counter: null,
    rarity: 'L',
    effect: '[DON!! x1] [When Attacking] (1): If you have a {FILM} type Character, draw 1 card.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP06-001',
    isAltArt: false,
    cardtraderSearch: 'Uta OP06-001',
    marketPriceEstimated: 11.00,
  },
  {
    id: 'OP06-021',
    set: 'OP-06',
    name: 'Perona',
    title: 'Ghost Princess',
    category: 'Leader',
    color: 'Green / Black',
    type: 'Thriller Bark Pirates',
    cost: null,
    life: 4,
    power: 5000,
    counter: null,
    rarity: 'L',
    effect: '[Activate: Main] [Once Per Turn] Choose 1: Rest up to 1 of your opponent\'s Characters with a cost of 4 or less, or give up to 1 of your opponent\'s Characters -1 cost during this turn.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP06-021',
    isAltArt: false,
    cardtraderSearch: 'Perona OP06-021',
    marketPriceEstimated: 16.50,
  },
  {
    id: 'OP06-042',
    set: 'OP-06',
    name: 'Yamato',
    title: 'Son of Oden',
    category: 'Leader',
    color: 'Green / Yellow',
    type: 'Land of Wano',
    cost: null,
    life: 4,
    power: 5000,
    counter: null,
    rarity: 'L',
    effect: '<Double Attack> [Opponent\'s Turn] If you have 2 or fewer Life cards, this Leader gains +1000 power.',
    attribute: 'Strike',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP06-042',
    isAltArt: false,
    cardtraderSearch: 'Yamato OP06-042',
    marketPriceEstimated: 25.00,
  },
  {
    id: 'OP06-080',
    set: 'OP-06',
    name: 'Gecko Moria',
    title: 'Shadow Asgard',
    category: 'Leader',
    color: 'Black',
    type: 'The Seven Warlords of the Sea / Thriller Bark Pirates',
    cost: null,
    life: 5,
    power: 5000,
    counter: null,
    rarity: 'L',
    effect: '[Activate: Main] [Once Per Turn] Trash 2 cards from the top of your deck: If there are 4 or more cards in your trash with {Thriller Bark Pirates}, give up to 1 of your Characters +1000 power.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP06-080',
    isAltArt: false,
    cardtraderSearch: 'Gecko Moria OP06-080',
    marketPriceEstimated: 28.00,
  },
  {
    id: 'OP06-086',
    set: 'OP-06',
    name: 'Gecko Moria (8-Cost)',
    title: 'Ruler of the Florian Triangle',
    category: 'Character',
    color: 'Black',
    type: 'The Seven Warlords of the Sea / Thriller Bark Pirates',
    cost: 8,
    life: null,
    power: 9000,
    counter: null,
    rarity: 'SR',
    effect: '[On Play] Choose up to 2 Character cards with a cost of 4 or less and different names from your trash: Play 1 rested and 1 active.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP06-086',
    isAltArt: false,
    cardtraderSearch: 'Gecko Moria OP06-086',
    marketPriceEstimated: 48.00,
  },
  {
    id: 'OP06-118',
    set: 'OP-06',
    name: 'Roronoa Zoro (9-Cost Secret)',
    title: 'King of Hell Three-Sword Serpent',
    category: 'Character',
    color: 'Green',
    type: 'Straw Hat Crew',
    cost: 9,
    life: null,
    power: 9000,
    counter: null,
    rarity: 'SEC',
    effect: '[Activate: Main] [Once Per Turn] (1): Set this Character as active. This card can attack up to 3 times in total per turn.',
    attribute: 'Slash',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP06-118',
    isAltArt: false,
    cardtraderSearch: 'Roronoa Zoro OP06-118',
    marketPriceEstimated: 60.00,
  },
  {
    id: 'OP06-118-MANGA',
    set: 'OP-06',
    name: 'Roronoa Zoro (Manga Rare)',
    title: 'Manga Parallel Art',
    category: 'Character',
    color: 'Green',
    type: 'Straw Hat Crew',
    cost: 9,
    life: null,
    power: 9000,
    counter: null,
    rarity: 'SP',
    effect: '[Activate: Main] [Once Per Turn] (1): Set this Character as active. This card can attack up to 3 times in total per turn.',
    attribute: 'Slash',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP06-118_p2',
    isAltArt: true,
    cardtraderSearch: 'Roronoa Zoro manga OP06-118',
    marketPriceEstimated: 1200.00,
  },

  // ==========================================
  // OP-07: 500 YEARS IN THE FUTURE
  // ==========================================
  {
    id: 'OP07-019',
    set: 'OP-07',
    name: 'Jewelry Bonney',
    title: 'Glutton',
    category: 'Leader',
    color: 'Green',
    type: 'Supernovas / Bonney Pirates',
    cost: null,
    life: 5,
    power: 5000,
    counter: null,
    rarity: 'L',
    effect: '[Opponent\'s Turn] [Once Per Turn] (1): When your opponent attacks, rest up to 1 of your opponent\'s Characters.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP07-019',
    isAltArt: false,
    cardtraderSearch: 'Jewelry Bonney OP07-019',
    marketPriceEstimated: 22.00,
  },
  {
    id: 'OP07-038',
    set: 'OP-07',
    name: 'Boa Hancock',
    title: 'Pirate Empress',
    category: 'Leader',
    color: 'Blue',
    type: 'The Seven Warlords of the Sea / Kuja Pirates',
    cost: null,
    life: 5,
    power: 5000,
    counter: null,
    rarity: 'L',
    effect: '[When Attacking] If you have 5 or fewer cards in your hand, draw 1 card.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP07-038',
    isAltArt: false,
    cardtraderSearch: 'Boa Hancock OP07-038',
    marketPriceEstimated: 18.00,
  },
  {
    id: 'OP07-038-MANGA',
    set: 'OP-07',
    name: 'Boa Hancock (Manga Rare)',
    title: 'Manga Parallel Art',
    category: 'Leader',
    color: 'Blue',
    type: 'The Seven Warlords of the Sea / Kuja Pirates',
    cost: null,
    life: 5,
    power: 5000,
    counter: null,
    rarity: 'SP',
    effect: '[When Attacking] If you have 5 or fewer cards in your hand, draw 1 card.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP07-038_p2',
    isAltArt: true,
    cardtraderSearch: 'Boa Hancock manga OP07-038',
    marketPriceEstimated: 1400.00,
  },
  {
    id: 'OP07-059',
    set: 'OP-07',
    name: 'Rob Lucci (Black Leader)',
    title: 'CP0 Masked Agent',
    category: 'Leader',
    color: 'Black',
    type: 'CP0',
    cost: null,
    life: 5,
    power: 5000,
    counter: null,
    rarity: 'L',
    effect: '[When Attacking] Trash 2 cards from the top of your deck: Give up to 1 of your opponent\'s Characters -1 cost during this turn.',
    attribute: 'Slash',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP07-059',
    isAltArt: false,
    cardtraderSearch: 'Rob Lucci OP07-059',
    marketPriceEstimated: 24.00,
  },
  {
    id: 'OP07-109',
    set: 'OP-07',
    name: 'Portgas.D.Ace (Secret)',
    title: 'Inherited Will',
    category: 'Character',
    color: 'Yellow',
    type: 'Whitebeard Pirates',
    cost: 10,
    life: null,
    power: 10000,
    counter: null,
    rarity: 'SEC',
    effect: '<Rush> [On Play] If you have 2 or fewer Life cards, add 1 card from the top of your deck to your Life cards.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP07-109',
    isAltArt: false,
    cardtraderSearch: 'Portgas D Ace OP07-109',
    marketPriceEstimated: 52.00,
  },

  // ==========================================
  // OP-08: TWO LEGENDS
  // ==========================================
  {
    id: 'OP08-001',
    set: 'OP-08',
    name: 'Tony Tony.Chopper',
    title: 'Doctor',
    category: 'Leader',
    color: 'Red / Green',
    type: 'Animal / Straw Hat Crew',
    cost: null,
    life: 4,
    power: 5000,
    counter: null,
    rarity: 'L',
    effect: '[DON!! x1] [When Attacking] Give up to 1 of your {Animal} type Characters +2000 power during this turn.',
    attribute: 'Strike',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP08-001',
    isAltArt: false,
    cardtraderSearch: 'Tony Tony Chopper OP08-001',
    marketPriceEstimated: 8.00,
  },
  {
    id: 'OP08-057',
    set: 'OP-08',
    name: 'Marco',
    title: 'The Phoenix',
    category: 'Leader',
    color: 'Blue / Red',
    type: 'Whitebeard Pirates',
    cost: null,
    life: 4,
    power: 5000,
    counter: null,
    rarity: 'L',
    effect: '[When Attacking] You may trash 1 card from your hand: Give up to 1 of your opponent\'s Characters -2000 power during this turn.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP08-057',
    isAltArt: false,
    cardtraderSearch: 'Marco OP08-057',
    marketPriceEstimated: 14.00,
  },
  {
    id: 'OP08-118',
    set: 'OP-08',
    name: 'Silvers Rayleigh',
    title: 'Dark King',
    category: 'Character',
    color: 'Red',
    type: 'Roger Pirates',
    cost: 8,
    life: null,
    power: 8000,
    counter: null,
    rarity: 'SEC',
    effect: '[On Play] Give up to 2 of your opponent\'s Characters -3000 power during this turn. Then, K.O. up to 1 of your opponent\'s Characters with 3000 or less power.',
    attribute: 'Slash',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP08-118',
    isAltArt: false,
    cardtraderSearch: 'Silvers Rayleigh OP08-118',
    marketPriceEstimated: 45.00,
  },
  {
    id: 'OP08-119',
    set: 'OP-08',
    name: 'Edward.Newgate (Secret)',
    title: 'Prime Whitebeard',
    category: 'Character',
    color: 'Blue',
    type: 'Whitebeard Pirates',
    cost: 9,
    life: null,
    power: 10000,
    counter: null,
    rarity: 'SEC',
    effect: '[On Play] Bottom deck up to 1 Character with 7000 or less power.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP08-119',
    isAltArt: false,
    cardtraderSearch: 'Edward Newgate OP08-119',
    marketPriceEstimated: 40.00,
  },

  // ==========================================
  // OP-09: THE FOUR EMPERORS
  // ==========================================
  {
    id: 'OP09-001',
    set: 'OP-09',
    name: 'Marshall.D.Teach',
    title: 'Blackbeard',
    category: 'Leader',
    color: 'Black',
    type: 'The Four Emperors / Blackbeard Pirates',
    cost: null,
    life: 5,
    power: 5000,
    counter: null,
    rarity: 'L',
    effect: '[Your Turn] Negate all [On Play] effects of your opponent\'s Characters. [End of Your Turn] Draw 1 card.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP09-001',
    isAltArt: false,
    cardtraderSearch: 'Marshall D Teach OP09-001',
    marketPriceEstimated: 38.00,
  },
  {
    id: 'OP09-004',
    set: 'OP-09',
    name: 'Buggy',
    title: 'Star Clown',
    category: 'Leader',
    color: 'Blue',
    type: 'The Four Emperors / Cross Guild',
    cost: null,
    life: 5,
    power: 5000,
    counter: null,
    rarity: 'L',
    effect: '[When Attacking] (1): Reveal cards from the top of your deck until you reveal a {Cross Guild} Character. Play it rested.',
    attribute: 'Slash',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP09-004',
    isAltArt: false,
    cardtraderSearch: 'Buggy OP09-004',
    marketPriceEstimated: 25.00,
  },
  {
    id: 'OP09-004-MANGA',
    set: 'OP-09',
    name: 'Buggy (Manga Rare)',
    title: 'Emperor Buggy Manga Art',
    category: 'Leader',
    color: 'Blue',
    type: 'The Four Emperors / Cross Guild',
    cost: null,
    life: 5,
    power: 5000,
    counter: null,
    rarity: 'SP',
    effect: '[When Attacking] (1): Reveal cards from the top of your deck until you reveal a {Cross Guild} Character. Play it rested.',
    attribute: 'Slash',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP09-004_p2',
    isAltArt: true,
    cardtraderSearch: 'Buggy manga OP09-004',
    marketPriceEstimated: 1100.00,
  },
  {
    id: 'OP09-021',
    set: 'OP-09',
    name: 'Shanks',
    title: 'Chief of Red Hair',
    category: 'Leader',
    color: 'Red',
    type: 'The Four Emperors / Red Hair Pirates',
    cost: null,
    life: 5,
    power: 5000,
    counter: null,
    rarity: 'L',
    effect: '[DON!! x1] [When Attacking] Give up to 1 of your opponent\'s Characters -1000 power during this turn.',
    attribute: 'Slash',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP09-021',
    isAltArt: false,
    cardtraderSearch: 'Shanks OP09-021',
    marketPriceEstimated: 26.00,
  },
  {
    id: 'OP09-051',
    set: 'OP-09',
    name: 'Kuzan (Aokiji)',
    title: 'Blackbeard Commander',
    category: 'Character',
    color: 'Black',
    type: 'Blackbeard Pirates',
    cost: 5,
    life: null,
    power: 6000,
    counter: 1000,
    rarity: 'SR',
    effect: '[On Play] Choose up to 1 of your opponent\'s Characters and give it -4 cost during this turn.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP09-051',
    isAltArt: false,
    cardtraderSearch: 'Kuzan OP09-051',
    marketPriceEstimated: 15.00,
  },
  {
    id: 'OP09-081',
    set: 'OP-09',
    name: 'Marshall.D.Teach (10-Cost)',
    title: 'Darkness and Quake',
    category: 'Character',
    color: 'Black',
    type: 'The Four Emperors / Blackbeard Pirates',
    cost: 10,
    life: null,
    power: 12000,
    counter: null,
    rarity: 'SR',
    effect: '[On Play] Negate the effect of your opponent\'s Leader and trash up to 1 Character with a cost of 6 or less.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP09-081',
    isAltArt: false,
    cardtraderSearch: 'Marshall D Teach OP09-081',
    marketPriceEstimated: 40.00,
  },
  {
    id: 'OP09-118',
    set: 'OP-09',
    name: 'Gol.D.Roger',
    title: 'Pirate King',
    category: 'Character',
    color: 'Red',
    type: 'Roger Pirates',
    cost: 10,
    life: null,
    power: 13000,
    counter: null,
    rarity: 'SEC',
    effect: '<Rush> <Cannot be K.O.\'d> [When Attacking] Trash 1 of your opponent\'s Life cards.',
    attribute: 'Slash',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP09-118',
    isAltArt: false,
    cardtraderSearch: 'Gol D Roger OP09-118',
    marketPriceEstimated: 95.00,
  },
  {
    id: 'OP09-118-MANGA',
    set: 'OP-09',
    name: 'Gol.D.Roger (Manga Rare)',
    title: 'He Laughed',
    category: 'Character',
    color: 'Red',
    type: 'Roger Pirates',
    cost: 10,
    life: null,
    power: 13000,
    counter: null,
    rarity: 'SP',
    effect: '<Rush> <Cannot be K.O.\'d> [When Attacking] Trash 1 of your opponent\'s Life cards.',
    attribute: 'Slash',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP09-118_p2',
    isAltArt: true,
    cardtraderSearch: 'Gol D Roger manga OP09-118',
    marketPriceEstimated: 3200.00,
  },
  {
    id: 'OP09-119',
    set: 'OP-09',
    name: 'Shanks (Secret Emperor)',
    title: 'Divine Departure',
    category: 'Character',
    color: 'Red',
    type: 'The Four Emperors / Red Hair Pirates',
    cost: 10,
    life: null,
    power: 12000,
    counter: null,
    rarity: 'SEC',
    effect: '<Rush> [When Attacking] K.O. up to 1 of your opponent\'s Characters with 10000 or less power.',
    attribute: 'Slash',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/OP09-119',
    isAltArt: false,
    cardtraderSearch: 'Shanks OP09-119',
    marketPriceEstimated: 75.00,
  },

  // ==========================================
  // ST-01: STRAW HAT CREW (STARTER DECK)
  // ==========================================
  {
    id: 'ST01-001',
    set: 'ST-01',
    name: 'Monkey.D.Luffy (Starter Leader)',
    title: 'Straw Hat Crew Captain',
    category: 'Leader',
    color: 'Red',
    type: 'Supernovas / Straw Hat Crew',
    cost: null,
    life: 5,
    power: 5000,
    counter: null,
    rarity: 'L',
    effect: '[Activate: Main] [Once Per Turn] Give this Leader or 1 of your Characters up to 1 rested DON!! card.',
    attribute: 'Strike',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/ST01-001',
    isAltArt: false,
    cardtraderSearch: 'Monkey D Luffy ST01-001',
    marketPriceEstimated: 2.50,
  },
  {
    id: 'ST01-004',
    set: 'ST-01',
    name: 'Sanji',
    title: 'Cook of the Baratie',
    category: 'Character',
    color: 'Red',
    type: 'Straw Hat Crew',
    cost: 2,
    life: null,
    power: 4000,
    counter: null,
    rarity: 'C',
    effect: '<Rush> (This card can attack on the turn in which it is played.)',
    attribute: 'Strike',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/ST01-004',
    isAltArt: false,
    cardtraderSearch: 'Sanji ST01-004',
    marketPriceEstimated: 1.50,
  },
  {
    id: 'ST01-006',
    set: 'ST-01',
    name: 'Tony Tony.Chopper',
    title: 'Cotton Candy Lover',
    category: 'Character',
    color: 'Red',
    type: 'Animal / Straw Hat Crew',
    cost: 1,
    life: null,
    power: 1000,
    counter: null,
    rarity: 'C',
    effect: '<Blocker> (After your opponent declares an attack, you may rest this card to make it the new target.)',
    attribute: 'Strike',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/ST01-006',
    isAltArt: false,
    cardtraderSearch: 'Chopper ST01-006',
    marketPriceEstimated: 2.00,
  },
  {
    id: 'ST01-011',
    set: 'ST-01',
    name: 'Brook',
    title: 'Soul King',
    category: 'Character',
    color: 'Red',
    type: 'Straw Hat Crew',
    cost: 4,
    life: null,
    power: 5000,
    counter: 1000,
    rarity: 'C',
    effect: '[On Play] Give up to 2 rested DON!! cards to your Leader or Character.',
    attribute: 'Slash',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/ST01-011',
    isAltArt: false,
    cardtraderSearch: 'Brook ST01-011',
    marketPriceEstimated: 1.00,
  },
  {
    id: 'ST01-012',
    set: 'ST-01',
    name: 'Roronoa Zoro (Starter)',
    title: 'Straw Hat Swordsman',
    category: 'Character',
    color: 'Red',
    type: 'Supernovas / Straw Hat Crew',
    cost: 3,
    life: null,
    power: 5000,
    counter: null,
    rarity: 'SR',
    effect: '[DON!! x1] This Character gains +1000 power.',
    attribute: 'Slash',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/ST01-012',
    isAltArt: false,
    cardtraderSearch: 'Roronoa Zoro ST01-012',
    marketPriceEstimated: 14.00,
  },
  {
    id: 'ST01-014',
    set: 'ST-01',
    name: 'Guard Point',
    title: 'Iron Defense',
    category: 'Event',
    color: 'Red',
    type: 'Animal / Straw Hat Crew',
    cost: 1,
    life: null,
    power: null,
    counter: null,
    rarity: 'C',
    effect: '[Counter] Up to 1 of your Leader or Character cards gains +3000 power during this battle.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/ST01-014',
    isAltArt: false,
    cardtraderSearch: 'Guard Point ST01-014',
    marketPriceEstimated: 1.20,
  },

  // ==========================================
  // ST-02: WORST GENERATION (STARTER DECK)
  // ==========================================
  {
    id: 'ST02-001',
    set: 'ST-02',
    name: 'Eustass"Captain"Kid (Starter Leader)',
    title: 'Captain of Kid Pirates',
    category: 'Leader',
    color: 'Green',
    type: 'Supernovas / Kid Pirates',
    cost: null,
    life: 5,
    power: 5000,
    counter: null,
    rarity: 'L',
    effect: '[Activate: Main] [Once Per Turn] (3) Trash 1 card from your hand: Set this Leader as active.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/ST02-001',
    isAltArt: false,
    cardtraderSearch: 'Eustass Captain Kid ST02-001',
    marketPriceEstimated: 3.50,
  },
  {
    id: 'ST02-004',
    set: 'ST-02',
    name: 'Killer',
    title: 'Massacre Soldier',
    category: 'Character',
    color: 'Green',
    type: 'Supernovas / Kid Pirates',
    cost: 3,
    life: null,
    power: 3000,
    counter: null,
    rarity: 'C',
    effect: '<Blocker> (After your opponent declares an attack, you may rest this card to make it the new target.)',
    attribute: 'Slash',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/ST02-004',
    isAltArt: false,
    cardtraderSearch: 'Killer ST02-004',
    marketPriceEstimated: 2.20,
  },
  {
    id: 'ST02-007',
    set: 'ST-02',
    name: 'Jewelry Bonney',
    title: 'Supernova Glutton',
    category: 'Character',
    color: 'Green',
    type: 'Supernovas / Bonney Pirates',
    cost: 1,
    life: null,
    power: 1000,
    counter: 1000,
    rarity: 'C',
    effect: '[Activate: Main] (1) Rest this card: Look at 5 cards from the top of your deck; reveal up to 1 {Supernovas} type card and add it to your hand.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/ST02-007',
    isAltArt: false,
    cardtraderSearch: 'Jewelry Bonney ST02-007',
    marketPriceEstimated: 9.50,
  },
  {
    id: 'ST02-013',
    set: 'ST-02',
    name: 'Eustass"Captain"Kid (Double Attack)',
    title: 'Magnetic Magnetism',
    category: 'Character',
    color: 'Green',
    type: 'Supernovas / Kid Pirates',
    cost: 7,
    life: null,
    power: 7000,
    counter: null,
    rarity: 'SR',
    effect: '<Double Attack> [DON!! x1] [End of Your Turn] Set this Character as active.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/ST02-013',
    isAltArt: false,
    cardtraderSearch: 'Eustass Captain Kid ST02-013',
    marketPriceEstimated: 12.00,
  },

  // ==========================================
  // ST-10: THE THREE CAPTAINS (ULTIMATE DECK)
  // ==========================================
  {
    id: 'ST10-001',
    set: 'ST-10',
    name: 'Trafalgar Law (Captain)',
    title: 'Red/Purple Law',
    category: 'Leader',
    color: 'Red / Purple',
    type: 'Heart Pirates / Supernovas',
    cost: null,
    life: 4,
    power: 5000,
    counter: null,
    rarity: 'L',
    effect: '[Activate: Main] [Once Per Turn] DON!! -3: Bottom deck up to 1 of your opponent\'s Characters with 3000 or less power. Then, play up to 1 Character with 4 or less cost from your hand.',
    attribute: 'Slash',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/ST10-001',
    isAltArt: false,
    cardtraderSearch: 'Trafalgar Law ST10-001',
    marketPriceEstimated: 28.00,
  },
  {
    id: 'ST10-002',
    set: 'ST-10',
    name: 'Monkey.D.Luffy (Captain)',
    title: 'Red/Purple Luffy',
    category: 'Leader',
    color: 'Red / Purple',
    type: 'Straw Hat Crew / Supernovas',
    cost: null,
    life: 4,
    power: 5000,
    counter: null,
    rarity: 'L',
    effect: '[Activate: Main] [Once Per Turn] Trash 1 card from your Life cards: Add 1 active DON!! card from your DON!! deck.',
    attribute: 'Strike',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/ST10-002',
    isAltArt: false,
    cardtraderSearch: 'Monkey D Luffy ST10-002',
    marketPriceEstimated: 19.00,
  },
  {
    id: 'ST10-006',
    set: 'ST-10',
    name: 'Monkey.D.Luffy (Rush 7-Cost)',
    title: 'Gear 4 Snakeman',
    category: 'Character',
    color: 'Purple',
    type: 'Straw Hat Crew',
    cost: 7,
    life: null,
    power: 7000,
    counter: null,
    rarity: 'SR',
    effect: '<Rush> [On Play] DON!! -1: This Character gains +1000 power during this turn.',
    attribute: 'Strike',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/ST10-006',
    isAltArt: false,
    cardtraderSearch: 'Monkey D Luffy ST10-006',
    marketPriceEstimated: 16.00,
  },

  // ==========================================
  // DON!! CARDS & SPECIAL PROMOS
  // ==========================================
  {
    id: 'DON-001',
    set: 'ALL',
    name: 'DON!! Card (Gold Stamp)',
    title: 'Official Gold Tournament Stamp',
    category: 'DON!!',
    color: 'Red',
    type: 'DON!!',
    cost: null,
    life: null,
    power: null,
    counter: null,
    rarity: 'C',
    effect: '[Your Turn] Give 1 of your Leaders or Characters +1000 power.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/DON-001',
    isAltArt: false,
    cardtraderSearch: 'DON!! card gold stamp one piece',
    marketPriceEstimated: 5.00,
  },
  {
    id: 'DON-002',
    set: 'ALL',
    name: 'DON!! Card (Gear 5 Luffy Manga)',
    title: 'Sun God Drums of Liberation',
    category: 'DON!!',
    color: 'Purple',
    type: 'DON!!',
    cost: null,
    life: null,
    power: null,
    counter: null,
    rarity: 'SP',
    effect: '[Your Turn] Give 1 of your Leaders or Characters +1000 power.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/DON-002',
    isAltArt: true,
    cardtraderSearch: 'DON!! gear 5 manga one piece',
    marketPriceEstimated: 35.00,
  },
  {
    id: 'DON-003',
    set: 'ALL',
    name: 'DON!! Card (Red Hair Pirates Shanks)',
    title: 'Divine Departure Edition',
    category: 'DON!!',
    color: 'Red',
    type: 'DON!!',
    cost: null,
    life: null,
    power: null,
    counter: null,
    rarity: 'SP',
    effect: '[Your Turn] Give 1 of your Leaders or Characters +1000 power.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/DON-003',
    isAltArt: true,
    cardtraderSearch: 'DON!! shanks one piece',
    marketPriceEstimated: 28.00,
  },
  {
    id: 'DON-004',
    set: 'ALL',
    name: 'DON!! Card (Whitebeard Jolly Roger)',
    title: 'Family of the Seas',
    category: 'DON!!',
    color: 'Red',
    type: 'DON!!',
    cost: null,
    life: null,
    power: null,
    counter: null,
    rarity: 'SP',
    effect: '[Your Turn] Give 1 of your Leaders or Characters +1000 power.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/DON-004',
    isAltArt: true,
    cardtraderSearch: 'DON!! whitebeard one piece',
    marketPriceEstimated: 22.00,
  },
  {
    id: 'DON-005',
    set: 'ALL',
    name: 'DON!! Card (Blackbeard Darkness)',
    title: 'Yami Yami no Mi Vortex',
    category: 'DON!!',
    color: 'Black',
    type: 'DON!!',
    cost: null,
    life: null,
    power: null,
    counter: null,
    rarity: 'SP',
    effect: '[Your Turn] Give 1 of your Leaders or Characters +1000 power.',
    attribute: 'Special',
    image: 'https://optcg-api.arjunbansal-ai.workers.dev/images/DON-005',
    isAltArt: true,
    cardtraderSearch: 'DON!! blackbeard one piece',
    marketPriceEstimated: 25.00,
  },
];

console.log(`Generated ${RAW_CARDS.length} official cards across ${SETS.length - 1} sets.`);

// 1. Write src/data/mockCards.js
const mockCardsContent = `// Comprehensive official dataset of One Piece TCG cards
// Sets included: OP-01 through OP-09, ST-01, ST-02, ST-10, and Special DON!! Cards

export const CARDTRADER_BASE_URL = 'https://www.cardtrader.com/es/games/one-piece-card-game?query=';

export const SETS = ${JSON.stringify(SETS, null, 2)};

export const COLORS = ${JSON.stringify(COLORS, null, 2)};

export const RARITIES = ${JSON.stringify(RARITIES, null, 2)};

export const INITIAL_CARDS = ${JSON.stringify(RAW_CARDS, null, 2)};
`;

fs.writeFileSync(path.join(__dirname, '../src/data/mockCards.js'), mockCardsContent, 'utf8');
console.log('Successfully wrote src/data/mockCards.js');

// 2. Generate supabase/migration_v0.6.0_cards_mass_import.sql
let sql = `-- ==============================================================================
-- GRAND LINE VAULT — INGESTIÓN MASIVA DE CARTAS OFICIALES (POSTGRESQL / SUPABASE)
-- Versión: v0.6.0
-- Sets incluidos: OP-01 a OP-09, ST-01, ST-02, ST-10, y cartas DON!!
-- ==============================================================================

INSERT INTO public.cards (
    id, set_id, name, title, category, color, card_type, 
    cost, life, power, counter, rarity, effect, attribute, 
    image_url, is_alt_art, cardtrader_search, estimated_price
) VALUES\n`;

const sqlValues = RAW_CARDS.map((c) => {
  const escapeSql = (str) => (str ? `'${str.replace(/'/g, "''")}'` : 'NULL');
  return `(
    ${escapeSql(c.id)},
    ${escapeSql(c.set)},
    ${escapeSql(c.name)},
    ${escapeSql(c.title)},
    ${escapeSql(c.category)},
    ${escapeSql(c.color)},
    ${escapeSql(c.type)},
    ${c.cost !== null ? c.cost : 'NULL'},
    ${c.life !== null ? c.life : 'NULL'},
    ${c.power !== null ? c.power : 'NULL'},
    ${c.counter !== null ? c.counter : 'NULL'},
    ${escapeSql(c.rarity)},
    ${escapeSql(c.effect)},
    ${escapeSql(c.attribute)},
    ${escapeSql(c.image)},
    ${c.isAltArt ? 'TRUE' : 'FALSE'},
    ${escapeSql(c.cardtraderSearch)},
    ${c.marketPriceEstimated.toFixed(2)}
  )`;
}).join(',\n');

sql += sqlValues;
sql += `\nON CONFLICT (id) DO UPDATE SET
    set_id = EXCLUDED.set_id,
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    color = EXCLUDED.color,
    card_type = EXCLUDED.card_type,
    cost = EXCLUDED.cost,
    life = EXCLUDED.life,
    power = EXCLUDED.power,
    counter = EXCLUDED.counter,
    rarity = EXCLUDED.rarity,
    effect = EXCLUDED.effect,
    attribute = EXCLUDED.attribute,
    image_url = EXCLUDED.image_url,
    is_alt_art = EXCLUDED.is_alt_art,
    cardtrader_search = EXCLUDED.cardtrader_search,
    estimated_price = EXCLUDED.estimated_price;\n`;

fs.writeFileSync(path.join(__dirname, '../supabase/migration_v0.6.0_cards_mass_import.sql'), sql, 'utf8');
console.log('Successfully wrote supabase/migration_v0.6.0_cards_mass_import.sql');
